name: Create DB POSTGRES AWS

on:
  workflow_dispatch:  # Permite que o destroy seja acionado manualmente

env:
  REGION_DEFAULT: ${{ vars.REGION_DEFAULT }}
  
jobs:
  create-db:
    name: terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Setup Terraform
        if: success()
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        working-directory: terraform_db_postgres
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: terraform_db_postgres
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        working-directory: terraform_db_postgres
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: terraform_db_postgres
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        working-directory: terraform_db_postgres
        run: terraform apply -input=false -auto-approve

      - name: Get Outputs from Terraform
        working-directory: terraform
        id: output
        run: |
          echo "::set-output name=db_instance_identifier::$(terraform output -raw db_instance_identifier)"
          echo "::set-output name=db_security_group_id::$(terraform output -raw db_security_group_id)"
          echo "::set-output name=db_subnet_group_id::$(terraform output -raw db_subnet_group_id)"

      - name: Update GitHub Env Variables
        run: |
          echo "DB_INSTANCE_IDENTIFIER=${{ steps.output.outputs.db_instance_identifier }}" >> $GITHUB_ENV
          echo "DB_SECURITY_GROUP_ID=${{ steps.output.outputs.db_security_group_id }}" >> $GITHUB_ENV
          echo "DB_SUBNET_GROUP_ID=${{ steps.output.outputs.db_subnet_group_id }}" >> $GITHUB_ENV