name: Create CLUSTER ESK AWS

on:
  workflow_dispatch: 

jobs:
  create-cluster:
    name: terraform
    runs-on: ubuntu-latest

    environment: production

    env:
      TF_VAR_regionDefault: ${{ vars.REGION_DEFAULT }}
      TF_VAR_projectName: ${{ vars.PROJECT_NAME }}
      TF_VAR_labRole: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole"
      TF_VAR_accessConfig: ${{ vars.ACCESS_CONFIG }}
      TF_VAR_nodeGrop: ${{ vars.NODE_GROUP }}
      TF_VAR_principalArn: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/voclabs"
      TF_VAR_policyArn: ${{ vars.POLICY_ARN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.REGION_DEFAULT }}

      - name: Setup Terraform
        if: success()
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        working-directory: terraform_cluster
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: terraform_cluster
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        working-directory: terraform_cluster
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: terraform_cluster
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        working-directory: terraform_cluster
        run: terraform apply -input=false -auto-approve
      
      - name: Get Outputs from Terraform
        working-directory: terraform_cluster
        id: output
        run: |
          echo "cluster_security_group_id=$(terraform output -raw cluster_security_group_id)" >> $GITHUB_OUTPUT

      - name: Update GitHub Env Variables
        run: |
          echo "CLUSTER_SECURITY_GROUP_ID=${{ steps.output.outputs.cluster_security_group_id }}" >> $GITHUB_ENV