name: Create CLUSTER TESTE

on:
  workflow_dispatch: 

jobs:
  create-cluster:
    name: terraform
    runs-on: ubuntu-latest
    environment: production  # Certifique-se de que esse ambiente contém a secret
    
    env:
      TF_VAR_regionDefault: ${{ vars.REGION_DEFAULT }}
      TF_VAR_projectName: ${{ vars.PROJECT_NAME }}
      TF_VAR_labRole: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole"
      TF_VAR_accessConfig: ${{ vars.ACCESS_CONFIG }}
      TF_VAR_nodeGrop: ${{ vars.NODE_GROUP }}
      TF_VAR_principalArn: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:voclabs"
      TF_VAR_policyArn: ${{ vars.POLICY_ARN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.REGION_DEFAULT }}
      - name: Debug Secrets
        run: echo "AWS_ACCOUNT_ID:" + ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Debug PrincipalArn
        run: echo "TF_VAR_principalArn:" +${{ env.TF_VAR_principalArn }}

      - name: Debug labRole
        run: echo "TF_VAR_labRole:" +${{ env.TF_VAR_labRole }}
