name: Create DB POSTGRES AWS

on:
  push:
    branches:
      - terraform-postgres
  pull_request:
    branches:
      - terraform-postgres

env:
  REGION_DEFAULT: "us-east-1"

jobs:
  create-db:
    name: terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Setup Terraform
        if: success()
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        working-directory: terraform_db_postgres
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: terraform_db_postgres
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        working-directory: terraform_db_postgres
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: terraform_db_postgres
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        working-directory: terraform_db_postgres
        run: terraform apply -input=false -auto-approve