name: Create Cluster ESK AWS

on:
  workflow_dispatch: 

env:
  REGION_DEFAULT: ${{ vars.REGION_DEFAULT }}

jobs:
  create-cluster:
    name: terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Setup Terraform
        if: success()
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        working-directory: terraform_cluster
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: terraform_cluster
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        working-directory: terraform_cluster
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: terraform_cluster
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        working-directory: terraform_cluster
        run: terraform apply -input=false -auto-approve
      
      - name: Get Outputs from Terraform
        working-directory: terraform_cluster
        id: output
        run: |
          echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
          echo "cluster_security_group_id=$(terraform output -raw cluster_security_group_id)" >> $GITHUB_OUTPUT
          echo "cluster_node_group_id=$(terraform output -raw cluster_node_group_id)" >> $GITHUB_OUTPUT
          echo "cluster_access_policy_id=$(terraform output -raw cluster_access_policy_id)" >> $GITHUB_OUTPUT
          echo "cluster_access_entry_id=$(terraform output -raw cluster_access_entry_id)" >> $GITHUB_OUTPUT

      - name: Update GitHub Env Variables
        run: |
          echo "CLUSTER_NAME=${{ steps.output.outputs.cluster_name }}" >> $GITHUB_ENV
          echo "CLUSTER_SECURITY_GROUP_ID=${{ steps.output.outputs.cluster_security_group_id }}" >> $GITHUB_ENV
          echo "CLUSTER_NODE_GROUP_ID=${{ steps.output.outputs.cluster_node_group_id }}" >> $GITHUB_ENV
          echo "CLUSTER_ACCESS_POLICY_ID=${{ steps.output.outputs.cluster_access_policy_id }}" >> $GITHUB_ENV
          echo "CLUSTER_ACCESS_ENTRY_ID=${{ steps.output.outputs.cluster_access_entry_id }}" >> $GITHUB_ENV